version: "3.8"
services:
  polardb-catalog:
    image: "postgres:13"
    container_name: "polardb-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog
  catalog-service:
    image: "polarbookshop/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # JVM environment variable to enable debug through a socket on port 8001
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-catalog:5432/polardb_catalog

  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order
  order-service:
    depends_on:
      - polardb-order
    image: "polarbookshop/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # JVM environment variable to enable debug through a socket on port 8002
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002
      - SPRING_R2DBC_URL=r2dbc:postgresql://polardb-order:5433/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polardb-order:5433/polardb_order
