apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog-service
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30001
