apiVersion: v1
kind: Service
metadata:
  name: polardb-catalog-service
  labels:
    db: polardb-catalog
spec:
  type: ClusterIP
  selector:
    db: polardb-catalog
  ports:
  - port: 5432
    targetPort: 5432
