apiVersion: apps/v1
kind: Deployment
metadata:
  name: polardb-catalog-deployment
  labels:
    db: polardb-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      db: polardb-catalog
  template:
    metadata:
      labels:
        db: polardb-catalog
    spec:
      containers:
      - name: polardb-catalog
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: polardb_catalog
